DROP TABLE IF EXISTS LOANS;
DROP TABLE IF EXISTS APPLICANTS;
DROP TABLE IF EXISTS LOAN_STATUS;

CREATE TABLE IF NOT EXISTS LOAN_STATUS(
STATUS_ID VARCHAR(3) PRIMARY KEY,
STATUS_DESCRIPTION VARCHAR(100) NOT NULL
);

INSERT INTO LOAN_STATUS (STATUS_ID, STATUS_DESCRIPTION) VALUES ('PND', 'PENDING'), ('APR', 'APPROVED'), ('REJ', 'REJECTED');

CREATE TABLE IF NOT EXISTS APPLICANTS(
APPLICANT_ID INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
APPLICANT_NAME VARCHAR(500) NOT NULL
);

CREATE TABLE IF NOT EXISTS  LOANS(
LOAN_ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
APPLICANT_ID INTEGER,
LOANED_AMOUNT NUMERIC NOT NULL,
STATUS_ID VARCHAR(3),
CREATED_AT TIMESTAMP DEFAULT NOW()::TIMESTAMP,
CREATED_BY VARCHAR(500) NOT NULL DEFAULT 'ADMIN',
MODIFIED_AT TIMESTAMP DEFAULT NOW()::TIMESTAMP,
MODIFIED_BY VARCHAR(500) NOT NULL  DEFAULT 'ADMIN',
CONSTRAINT FK_APPLICANT
	FOREIGN KEY(APPLICANT_ID)
		REFERENCES APPLICANTS(APPLICANT_ID),
CONSTRAINT FK_STATUS
	FOREIGN KEY(STATUS_ID)
		REFERENCES LOAN_STATUS(STATUS_ID)
);
